### ISSUE TITLE
Projects "Northwind.Service", "Northwind.Data" is not used in the solution?

### ISSUE THREAD

**Issue by it19862** [NBull92/Northwind-MVVM-Survival-Guide#1]
Projects `Northwind.Service`, `Northwind.Data` is not used in the solution?

![21 10 2022_12-43-04](https://user-images.githubusercontent.com/18245828/197344471-da303e7b-6308-40cf-aab7-a6fc9035c5c3.png)

**Comment by NBull92** [comment]
I wrote this code while working through the "MVVM Survival Guide for Enterprise Architectures in Silverlight and WPF Paperback – 2012" book. Therefore, the projects might not be used within the solution in it's final form. However, they are used in the solution at various stages throughout the book.
